services:
  system-status:
    image: ghcr.io/davebco/system-status-page:latest
    environment:
      - HOST_HOSTNAME=${HOSTNAME}
    ports:
      - "8085:8085"
    deploy:
      restart_policy:
        condition: on-failure
