services:
  system-status:
    image: ghcr.io/davebco/system-status-page:latest
    volumes:
      - /etc/hostname:/etc/host_hostname:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - "8085:8085"
    deploy:
      restart_policy:
        condition: on-failure
